Added OWNERS file in install_yamls
openstack-k8s-operators/install_yamls pull request #107
Opened 2023-02-15 06:58 UTC by amolkahat

2023-02-15 09:02 UTC, sandeepyadav93 requested changes

2023-02-15 09:02 UTC, sandeepyadav93 commented on OWNERS
> +# DO NOT EDIT; this file is auto-generated using https://github.com/openshift/ci-tools.
Remove these comments..
Please see examples here: https://github.com/openstack-k8s-operators/keystone-operator/blob/master/OWNERS

2023-02-15 09:02 UTC, sandeepyadav93 commented on OWNERS
> +options: {}
not needed

2023-02-15 09:04 UTC, amolkahat commented on OWNERS
> +options: {}
Done.

2023-02-15 09:04 UTC, amolkahat commented on OWNERS
> +# DO NOT EDIT; this file is auto-generated using https://github.com/openshift/ci-tools.
Done.

2023-02-15 11:36 UTC, abays approved these changes
/lgtm

2023-02-16 07:58 UTC, fmount approved these changes

2023-02-16 07:59 UTC, merged