Disable bmo_setup in zuul job
openstack-k8s-operators/install_yamls pull request #255
Opened 2023-05-10 09:39 UTC by raukadah

2023-05-10 12:50 UTC, raukadah commented
recheck

2023-05-10 14:57 UTC, karelyatin approved these changes

2023-05-10 15:08 UTC, fao89 approved these changes

2023-05-11 04:32 UTC, raukadah commented
recheck

2023-05-11 05:49 UTC, rabi requested changes
Without BMO  openstack-baremetal-controller would crash. We should not drop that.

2023-05-11 05:57 UTC, rabi reviewed
Looks like it's only changed in the rdo edpm job where crc is constrained with resources. That should be fine I guess.

2023-05-11 06:41 UTC, karelyatin requested changes

2023-05-11 06:41 UTC, karelyatin commented on ci/playbooks/deploy_podified_openstack.yaml
> +          -p='[{"op": "replace", "path": "/spec/rabbitmq/templates/rabbitmq/resources/requests/cpu", "value": 500Mi}]'
cpu should be 500m, not sure if 500Mi works

2023-05-11 06:41 UTC, karelyatin commented on ci/playbooks/deploy_podified_openstack.yaml
> +          -p='[{"op": "replace", "path": "/spec/rabbitmq/templates/rabbitmq/resources/requests/cpu", "value": 500Mi}]'
looking job logs i don't see rabbitmq pods so seems related.

2023-05-11 07:44 UTC, karelyatin approved these changes
/lgtm

2023-05-11 07:51 UTC, merged