Deploy N EDPM nodes
openstack-k8s-operators/install_yamls pull request #277
Opened 2023-05-17 11:40 UTC by fao89

2023-05-17 19:03 UTC, fultonj reviewed
I normally just loop on the make command so I'm not sure this patch is necessary.
```
 for I in $(seq 0 $NODES); do
  make edpm_compute EDPM_COMPUTE_SUFFIX=$I
done
```
Did someone request it or does the CI need it?

If we're going to have this loop do we also want to add it to `edpm_compute_repos`? If we don't we'd just loop it anway.

nit: should the variable name of the loop `for number` be capitalized `for NUMBER`?

Overall, I think we need to determine if we need the patch to add the loop when the user can just use their own loop.

2023-05-17 19:31 UTC, fao89 commented
@fultonj I agree, I'll drop the loop.
About `edpm_compute_repos` instead of looping, I believe we can use a service:
https://github.com/openstack-k8s-operators/dataplane-operator/pull/189
the idea is making easier to do scale tests (OSP-23847), so instead of calling `edpm_compute_repos` 200 times, it would be better t have it set in parallel through AEE

2023-05-17 20:58 UTC, slagle requested changes

2023-05-17 20:58 UTC, slagle commented on devsetup/Makefile
> +.PHONY: edpm_nodes
I think this target could probably just take the place of edpm_compute/edpm_compute_cleanup. No reason to have multiple ways of doing it. If you just want one node, you'd set EDPM_TOTAL_NODES=1.

2023-05-17 20:58 UTC, slagle commented on devsetup/Makefile
>  	scripts/edpm-compute-repos.sh ${EDPM_COMPUTE_SUFFIX}
I'd then add the loop here as well so that you don't need to call this target multiple times.

2023-05-18 15:17 UTC, fao89 commented on scripts/gen-edpm-kustomize.sh
> +      - repo-setup
requires: https://github.com/openstack-k8s-operators/dataplane-operator/pull/189

2023-05-18 19:05 UTC, fultonj reviewed
Looks good to me but I didn't test it in my environment yet.

2023-05-19 19:05 UTC, fao89 commented
recheck

2023-05-22 20:24 UTC, fao89 commented
recheck

2023-05-22 23:18 UTC, fao89 commented
recheck

2023-05-23 00:16 UTC, merged