Adding support for adoption scenario 1
openstack-k8s-operators/install_yamls pull request #818
Opened 2024-05-02 13:32 UTC by averdagu

Dataplane adoption docs supports doing the adoption while wallaby environment uses different subnets than next generation. This commit enables Makefiles in order to prepare the environment with different subnets between environments.

Related: [OSPRH-5881](https://issues.redhat.com//browse/OSPRH-5881)

2024-05-13 20:50 UTC, booxter commented on Makefile
> +ADOPTED_SCENARIO					?=false
names of variables here should not refer to adoption. There's a general case for deploying CP and DP services in different ranges. We should be able to stand up greenfield deployment with different ranges.

2024-05-13 21:00 UTC, booxter requested changes
Could you please give a playbook of commands that one would use to deploy the setup as you intend? Please add them to commit message.

Please also fix pre-commits.

2024-05-13 21:00 UTC, booxter commented on scripts/gen-nncp.sh
> +    if [ -n "$IPV6_ENABLED" ]; then
hm. why is it needed?

2024-05-31 16:02 UTC, averdagu commented
recheck

2024-06-05 12:02 UTC, averdagu commented
recheck

2024-06-06 15:49 UTC, averdagu commented
recheck

2024-06-14 15:40 UTC, fao89 commented
/approve

2024-10-07 06:56 UTC, danpawlik commented
recheck

2024-11-14 16:08 UTC, booxter approved these changes

2024-11-14 16:11 UTC, merged